import Head from "next/head";
import { ReactElement } from "react";
import { HomeLayout } from "src/component/Layouts/HomeLayout";
import type { NextPageWithLayout } from "src/pages/_app";

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className="text-red-300">aaaa</p>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <HomeLayout>{page}</HomeLayout>;
};

export default Home;
